//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Disasmo.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.8.1.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PathToCoreCLR_V3 {
            get {
                return ((string)(this["PathToCoreCLR_V3"]));
            }
            set {
                this["PathToCoreCLR_V3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool JitDumpInsteadOfDisasm_V3 {
            get {
                return ((bool)(this["JitDumpInsteadOfDisasm_V3"]));
            }
            set {
                this["JitDumpInsteadOfDisasm_V3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ShowAsmComments_V3 {
            get {
                return ((bool)(this["ShowAsmComments_V3"]));
            }
            set {
                this["ShowAsmComments_V3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("COMPlus_TieredCompilation=0;COMPlus_TC_QuickJitForLoops=1;COMPlus_TC_CallCountThr" +
            "eshold=1;COMPlus_TC_CallCountingDelayMs=10;COMPlus_JitDiffableDasm=1;COMPlus_Rea" +
            "dyToRun=0;COMPlus_ZapDisable=1;COMPlus_TieredPGO=1;")]
        public string CustomEnvVars3_V3 {
            get {
                return ((string)(this["CustomEnvVars3_V3"]));
            }
            set {
                this["CustomEnvVars3_V3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AllowDisasmInvocations_V3 {
            get {
                return ((bool)(this["AllowDisasmInvocations_V3"]));
            }
            set {
                this["AllowDisasmInvocations_V3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool UseDotnetBuildForReload_V3 {
            get {
                return ((bool)(this["UseDotnetBuildForReload_V3"]));
            }
            set {
                this["UseDotnetBuildForReload_V3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool RunAppMode_V3 {
            get {
                return ((bool)(this["RunAppMode_V3"]));
            }
            set {
                this["RunAppMode_V3"] = value;
            }
        }
    }
}
